server:
  port: 8081
#  servlet:
#    context-path: /experiment

spring:
  datasource:
    username: root
    password: 123456qwer
    url: jdbc:mysql://1.12.235.216:3306/experiment?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#    experiment-path-pattern: /experiment/**
#  resources:
#    experiment-locations: classpath:/experiment/
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.xy.experiment.entity

#showSql
logging:
  level:
    com:
      example:
        mapper: info

jasypt:
  encryptor:
    password: experiment

mail:
  host: smtp.exmail.qq.com
  port: 465
  username: Payne.SeediqBale@foxmail.com
  password: ae7d703E9C8fb83c
  form: Payne.SeediqBale@foxmail.com
  timeout: 25000
  protocol: smtp
  auth: true

virtual:
  serverURI: http://202.205.145.156:8017
  loginId: 100400
  secret: fjbr43
  aeskey: s818nmsYyGFp2hX6aRiKb23eD0TxQdU68jnfMnV/C/k=
  issueId: 100327
  save:
    urlprefix: /root/www/logs/
xcloud:
  uploadPath: /root/www/logs/



