server:
  port: 8081
#  servlet:
#    context-path: /experiment

spring:
  datasource:
    username: dev
    password: 321456qwer
    url: jdbc:mysql://11.122.235.216:3306/experiment?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#    experiment-path-pattern: /experiment/**
#  resources:
#    experiment-locations: classpath:/experiment/
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.xy.experiment.entity
  configuration:
    map-underscore-to-camel-case: true

#showSql
logging:
  level:
    com:
      example:
        mapper: info

jasypt:
  encryptor:
    password: experiment

mail:
  host: smtp.exmail.qq.com
  port: 465
  username: Payne.SeediqBale@foxmail.com
  password: ae7d703E9C8fb833
  form: Payne.SeediqBale@foxmail.com
  timeout: 25000
  protocol: smtp
  auth: true

virtual:
  serverURI: http://202.205.145.256:8011
  loginId: 100401
  secret: sjbr43
  aeskey: 2818nmsYyGFp2hX6aRiKb23eD0TxQdU68jnfMnV/C/k=
  issueId: 100327
  save:
    urlprefix: /root/www/logs/
xcloud:
  uploadPath: /root/www/logs/

experiment:
  isOpenEmail: false
  exeDownPath: /exp/download/
  vrExeName: VRSinusOpening.exe
  peExeName: penicillin.rar
#  exeDownPath: D:\\exp\\