server:
  port: 8081
#  servlet:
#    context-path: /experiment

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.64.40.243:3306/experiment?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#    experiment-path-pattern: /experiment/**
#  resources:
#    experiment-locations: classpath:/experiment/
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.xy.experiment.entity
  configuration:
    map-underscore-to-camel-case: true

#showSql
logging:
  level:
    com:
      example:
        mapper: info

jasypt:
  encryptor:
    password: experiment

mail:
  host: smtp.exmail.qq.com
  port: 465
  username: Payne.SeediqBale@foxmail.com
  password: ae7d703E9C8fb83c
  form: Payne.SeediqBale@foxmail.com
  timeout: 25000
  protocol: smtp
  auth: true

virtual:
  serverURI: http://202.205.145.156:8017
  loginId: 100400
  secret: fjbr43
  aeskey: s818nmsYyGFp2hX6aRiKb23eD0TxQdU68jnfMnV/C/k=
  issueId: 100327
  save:
    urlprefix: /root/www/logs/
xcloud:
  uploadPath: /root/www/logs/

experiment:
  isOpenEmail: false
  exeDownPath: /exp/download/
  vrExeName: 20221118_1848.rar
  peExeName: 20221118_1848.rar

jetcache:
  statIntervalMinutes: 15 # 统计间隔，默认0：表示不统计
  areaInCacheName: false  # areaName是否作为缓存key前缀，默认True
  local:
    default: # 默认default，可以配置更多的area
      type: linkedhashmap # 已支持可选：linkedhashmap、caffeine
      keyConvertor: fastjson # key转换器
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java # 序列化器,只有remote需要
      valueDecoder: java # 序列化器,只有remote需要
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
      password: qwer1234